name: Auto Assign to Project(s)

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  assign_to_project:
    runs-on: ubuntu-latest
    name: Assign Issues and/or PRs to Project ${{ inputs.project }}
    steps:
    - name: Assign to project
      uses: srggrs/assign-one-project-github-action@1.2.1
      with:
        project: https://github.com/orgs/newrelic/projects/41
