name: AWS SDK Smoke Tests

on:
  push:
  schedule:
    - cron:  '0 9 * * 1-5'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      # Purposely running install so it gets latest of aws sdk
      run: npm install 
    - name: Run Smoke Tests
      run: npm run smoke
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
